workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Set iOS Deployment Target to 16.0
        script: |
          echo "Updating deployment target to 16.0"
          
          # Update deployment target in Podfile
          if grep -q "platform :ios" ios/Podfile; then
            sed -i '' 's/platform :ios, .*/platform :ios, '\''16.0'\''/' ios/Podfile
          else
            echo "platform :ios, '16.0'" >> ios/Podfile
          fi

          flutter clean
          flutter pub get
          flutter build ios --simulator
    artifacts:
      - build/ios/iphonesimulator/*.app
