workflows:
  ios-simulator:
    name: iOS Simulator Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Set iOS Deployment Target to 15.5
        script: |
          sed -i '' 's/PLATFORM_VERSION = [0-9.]*/PLATFORM_VERSION = 15.5/' ios/Flutter/Generated.xcconfig || true
          sed -i '' 's/ios', '.*'/ios', '15.5'/' ios/Podfile || true
      - name: Install dependencies
        script: flutter pub get
      - name: Build for iOS Simulator
        script: flutter build ios --simulator
    artifacts:
      - build/ios/iphonesimulator/*.app
    publishing:
      email:
        recipients:
          - your-email@example.com
