workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Build for iOS Simulator
        script: |
          flutter clean
          flutter pub get
          flutter build ios --simulator
    artifacts:
      - build/ios/iphonesimulator/*.app
